###
GET http://localhost:8080/shopping-list/?customerLastName=Alekseev

###
GET http://localhost:8080/shopping-list/customers

###

GET http://localhost:8080/shopping-list/goods

###

PUT http://localhost:8080/shopping-list/new
Accept: application/json
Content-Type: application/json

{
  "productId": "26730108-99d1-4d3c-81f7-c7e8130272c6",
  "customerId": "d0dec015-cb19-4754-b92b-19bd695ff16e",
  "count": 5
}

###

DELETE http://localhost:8080/shopping-list/delete
Accept: application/json
Content-Type: application/json

{
  "productId": "26730108-99d1-4d3c-81f7-c7e8130272c6",
  "customerId": "d0dec015-cb19-4754-b92b-19bd695ff16e"
}